# Generated by Django 2.1.3 on 2019-02-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(choices=[('K', 'Kerosene'), ('P', 'Petrol'), ('S', 'Super')], default='K', max_length=1, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Product')),
            ],
            options={
                'ordering': ['-pk', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Product')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Station')),
            ],
        ),
        migrations.CreateModel(
            name='UserStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sms.Station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salerecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Station'),
        ),
        migrations.AlterUniqueTogether(
            name='userstation',
            unique_together={('user', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='stationproductprice',
            unique_together={('product', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='salerecord',
            unique_together={('station', 'product', 'entry_at')},
        ),
    ]
