# Generated by Django 2.1.3 on 2019-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='price_for',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='entry_at',
            field=models.DateField(),
        ),
    ]
