# Generated by Django 2.1.3 on 2019-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_remove_salerecord_price_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='price_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
