# Generated by Django 2.1.3 on 2019-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_auto_20190207_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='product_price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
