# Generated by Django 2.1.3 on 2019-02-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_salerecord_product_price_per_litre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='total_amount_collected',
            new_name='amount_collected',
        ),
        migrations.RenameField(
            model_name='salerecord',
            old_name='product_price_per_litre',
            new_name='price_per_litre',
        ),
    ]
