# Generated by Django 2.1.3 on 2019-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20190207_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='amount_collected',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
