# Generated by Django 2.1.3 on 2019-02-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20190207_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerecord',
            options={'ordering': ['-entry_at', 'product']},
        ),
    ]
