# Generated by Django 2.1.3 on 2019-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_auto_20190207_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='entry_at',
            field=models.DateField(help_text='YYYY-MM-dd'),
        ),
    ]
