# Generated by Django 2.1.3 on 2019-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_auto_20190207_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='entry_at',
            field=models.DateField(),
        ),
    ]
