# Generated by Django 2.1.3 on 2019-02-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_auto_20190207_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerecord',
            options={'ordering': ['-entry_at']},
        ),
    ]
